version: "3"
services:
  focalboard-db:
    image: postgres:latest
    container_name: focalboard-postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: boards
      POSTGRES_USER: boardsuser
      POSTGRES_PASSWORD: boardsuser-password

  focalboard:
    image: navystack/focalboard:openresty
    container_name: focalboard
    volumes:
      - fbdata:/opt/focalboard/data
      - ./config-dev.json:/opt/focalboard/config.json
      - ./nginx/default-dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8282:8000
    depends_on:
      - focalboard-db
    restart: unless-stopped

volumes:
  fbdata:
  pgdata:
