name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "Dockerfile"
      - "*.Dockerfile"
      - "**/*.Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@v3
        with:
          host: ${{ secrets.SSH_HOST_FOCALBOARD }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY_FOCALBOARD }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: ${{ secrets.FOCALBOARD_ENDPOINT_RUNNER }}
          append: |
            - endpoint: ${{ secrets.FOCALBOARD_ENDPOINT_ARM64 }}
              platforms: linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: set env
        run: echo "NOW=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Docker Build and Push (NODE_BUILDER)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            navystack/focalboard:nodebuild-cache
          file: Dockerfiles/nodebuild.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=registry,ref=navystack/focalboard:nodebuild-cache
          cache-to: type=registry,ref=navystack/focalboard:nodebuild-cache,mode=max

      - name: Docker Build and Push (GO_BUILDER)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            navystack/focalboard:gobuild-cache
          file: Dockerfiles/gobuild.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: type=registry,ref=navystack/focalboard:gobuild-cache
          cache-to: type=registry,ref=navystack/focalboard:gobuild-cache,mode=max

      - name: Docker Build and Push (Focalboard Only)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            navystack/focalboard:latest-${{ env.NOW }}
            navystack/focalboard:latest
            navystack/focalboard:7.12.0
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: ${{ secrets.BUILD_CACHE_FROM }}
          cache-to: ${{ secrets.BUILD_CACHE_TO }}

      - name: Docker Build and Push (with Nginx)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            navystack/focalboard:nginx-${{ env.NOW }}
            navystack/focalboard:nginx
          file: Nginx.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: ${{ secrets.BUILD_CACHE_FROM }}
          cache-to: ${{ secrets.BUILD_CACHE_TO }}

      - name: Docker Build and Push (with Openresty)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            navystack/focalboard:openresty-${{ env.NOW }}
            navystack/focalboard:openresty
          file: Openresty.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          cache-from: ${{ secrets.BUILD_CACHE_FROM }}
          cache-to: ${{ secrets.BUILD_CACHE_TO }}
